version: "2"
services:
  test_flask:
    image: "test-flask:latest"
    container_name: flask-app
    hostname: flask
    restart: "on-failure"
    expose:
      - "5000"
    ports:
      - "5000:5000"
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"
